<<<<<<< HEAD
version: '3.8'

services:

  db:
    image: postgres:17-alpine
    container_name: hrms
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vaishnavi@766
      POSTGRES_DB: hrms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./local_data.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image:  pranav091104/hrms-backend:latest 
    env_file:
      - ./.env
    container_name: hrms_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:Vaishnavi%40766@db:5432/hrms
      JWT_SECRET: your_jwt_secret
      JWT_EXPIRES_IN: 1d
      CLIENT_URL: http://localhost:3000
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USER: pranavpawale136@gmail.com
      MAIL_PASS: baxpliiwxydnjgci
    depends_on:
      db:
        condition: service_healthy
    command: >
        sh -c "node index.js"
volumes:
  postgres_data:

=======
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_pass
      KC_SMTP_HOST: smtp.gmail.com
      KC_SMTP_PORT: 465
      KC_SMTP_FROM: pranavpawale913@gmail.com
      KC_SMTP_AUTH: true
      KC_SMTP_USER: pranavpawale913@gmail.com
      KC_SMTP_PASSWORD:  tfwnouiuyoscdpol
      KC_SMTP_SSL: true
      KC_SPI_EMAIL_SMTP_STARTTLS: false
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    networks:
      - app-network

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_pass
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  keycloak_db_data:

networks:
  app-network:
    driver: bridge
>>>>>>> b4fb8b0bec2fd78eef6cc334bde511aa71d462c2
